name: CI

on:
 push:
    branches: [ main ]
 pull_request:
    branches: [ main ]

jobs:
 build:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [12.x, 14.x, 16.x, 18.x, 19.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
    # - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        # node-version: ${{ matrix.node-version }}
    - name: Copy env files
      run: cp .env.example .env && cp react/.env.example react/.env
    - name: Install dependencies
      run: npm install
    - name: Run setup
      run: npm run setup
    # TODO
    # - name: Test server and nodejs endpoints
    #   run: npm test
    - name: Test React
      run: npm run build:react

